# Node image
FROM node:20-alpine AS build

WORKDIR /app

# Install dependencies
COPY comments-spa-app/package*.json ./
RUN npm install

# Copy application sources
COPY comments-spa-app ./
RUN npm run build

# Nginx
FROM nginx:alpine
WORKDIR /usr/share/nginx/html

RUN rm -rf ./*
COPY --from=build /app/build .
COPY comments-spa-app/nginx/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD [ "nginx", "-g", "daemon off;" ]