--
-- PostgreSQL database dump
--

-- Dumped from database version 16.9
-- Dumped by pg_dump version 16.9

-- Started on 2025-12-11 12:28:02

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 219 (class 1259 OID 42672)
-- Name: Attachments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Attachments" (
    "Id" integer NOT NULL,
    "CommentId" integer NOT NULL,
    "OriginalFileName" character varying(260) NOT NULL,
    "StoredFileName" character varying(260) NOT NULL,
    "RelativePath" character varying(500) NOT NULL,
    "Type" integer NOT NULL,
    "SizeBytes" bigint NOT NULL,
    "MimeType" character varying(100),
    "Width" integer,
    "Height" integer
);


ALTER TABLE public."Attachments" OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 42671)
-- Name: Attachments_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Attachments" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Attachments_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 42659)
-- Name: Comments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Comments" (
    "Id" integer NOT NULL,
    "ParentId" integer,
    "UserName" character varying(50) NOT NULL,
    "Email" character varying(100) NOT NULL,
    "HomePage" character varying(200),
    "RawText" character varying(4000) NOT NULL,
    "SanitizedText" character varying(4000) NOT NULL,
    "UserIp" character varying(50),
    "UserAgent" character varying(512),
    "CreatedAtUtc" timestamp with time zone NOT NULL
);


ALTER TABLE public."Comments" OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 42658)
-- Name: Comments_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Comments" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Comments_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 42653)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 4751 (class 2606 OID 42678)
-- Name: Attachments PK_Attachments; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Attachments"
    ADD CONSTRAINT "PK_Attachments" PRIMARY KEY ("Id");


--
-- TOC entry 4748 (class 2606 OID 42665)
-- Name: Comments PK_Comments; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Comments"
    ADD CONSTRAINT "PK_Comments" PRIMARY KEY ("Id");


--
-- TOC entry 4745 (class 2606 OID 42657)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 4749 (class 1259 OID 42684)
-- Name: IX_Attachments_CommentId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Attachments_CommentId" ON public."Attachments" USING btree ("CommentId");


--
-- TOC entry 4746 (class 1259 OID 42685)
-- Name: IX_Comments_ParentId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Comments_ParentId" ON public."Comments" USING btree ("ParentId");


--
-- TOC entry 4753 (class 2606 OID 42679)
-- Name: Attachments FK_Attachments_Comments_CommentId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Attachments"
    ADD CONSTRAINT "FK_Attachments_Comments_CommentId" FOREIGN KEY ("CommentId") REFERENCES public."Comments"("Id") ON DELETE CASCADE;


--
-- TOC entry 4752 (class 2606 OID 42666)
-- Name: Comments FK_Comments_Comments_ParentId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Comments"
    ADD CONSTRAINT "FK_Comments_Comments_ParentId" FOREIGN KEY ("ParentId") REFERENCES public."Comments"("Id") ON DELETE RESTRICT;


-- Completed on 2025-12-11 12:28:02

--
-- PostgreSQL database dump complete
--

